package:
  image:
    name: gradle:jdk11@sha256:31cf1785883f562fc9f31ab85a339eaf201ecd1ea6a2c7fc50f51170de8b7826
  script:
    - gradle jar shadowjar
    - gradle -b legacy-build.gradle shadowjar
  artifacts:
    paths:
      - build/libs/keycloak-scim-1.0-SNAPSHOT.jar
      - build/libs/keycloak-scim-1.0-SNAPSHOT-all.jar
      - build/libs/keycloak-scim-1.0-SNAPSHOT-all-legacy.jar
  only:
    - main
