package:
  image:
    name: gradle:jdk11@sha256:5a2f8e1e382d37b3afdc0ec9d0c7e7a8d71fcc0753b3a24bf82e0a20af238f65
  script:
    - gradle jar shadowjar
    - gradle -b legacy-build.gradle shadowjar
  artifacts:
    paths:
      - build/libs/keycloak-scim-1.0-SNAPSHOT.jar
      - build/libs/keycloak-scim-1.0-SNAPSHOT-all.jar
      - build/libs/keycloak-scim-1.0-SNAPSHOT-all-legacy.jar
  only:
    - main
