package:
  image:
    name: gradle:jdk11@sha256:6a082e8cbbe2026a250c35faf4944b1f4ebb0e2a38e3e4f2d0d9326c5a6d09d8
  script:
    - gradle jar shadowjar
    - gradle -b legacy-build.gradle shadowjar
  artifacts:
    paths:
      - build/libs/keycloak-scim-1.0-SNAPSHOT.jar
      - build/libs/keycloak-scim-1.0-SNAPSHOT-all.jar
      - build/libs/keycloak-scim-1.0-SNAPSHOT-all-legacy.jar
  only:
    - main
